---
# This playbook stops the Cassandra service on the seed nodes, then the non-seeds, one at time.

- name: stop Cassandra service
  gather_facts: false
  hosts:
    - '{{ host_list }}'
  serial: 1

  tasks:
    - name: nodetool drain
      shell: "nodetool drain"
      ignore_errors: true

    - name: stop Cassandra service
      service:
        name: cassandra
        state: stopped
